# Generated by Django 5.1.3 on 2024-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_day', models.CharField(max_length=50)),
                ('truck_departure_time', models.CharField(max_length=50)),
                ('truck_truck', models.CharField(max_length=50)),
                ('truck_number', models.CharField(max_length=50)),
                ('truck_origin', models.CharField(max_length=50)),
                ('truck_destination', models.CharField(max_length=50)),
                ('truck_operator', models.CharField(max_length=50)),
                ('truck_coloader', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_coolie', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_adr', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_street', models.CharField(max_length=100)),
                ('truck_street_number', models.CharField(max_length=100)),
                ('truck_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('truck_city', models.CharField(max_length=50)),
                ('truck_country', models.CharField(max_length=50)),
                ('phone_country_code', models.CharField(max_length=4)),
                ('phone_area_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=4)),
            ],
        ),
    ]
